GOFMT_FILES?=$$(find . -name '*.go')

all: fmt build

fmt:
	gofmt -w $(GOFMT_FILES)

lint:
	go vet

image:
	docker build -t {{ .opts.Name }} .

graphql:
	go get
	dashi g graphql

build: graphql
	go mod tidy
	go build -ldflags "-X {{ .opts.Package }}/cmd.Version=`git rev-parse HEAD`" -o ./bin/{{ .opts.Name }}
	go install
